USE [master]
GO

/****** Object:  Database [BusStopManagement]    Script Date: 11/10/2020 12:40:26 PM ******/
CREATE DATABASE [BusStopManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BusStopManagement', FILENAME = N'F:\sqldata\BusStopManagement.mdf' , SIZE = 197632KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BusStopManagement_log', FILENAME = N'E:\sqllog\BusStopManagement_log.ldf' , SIZE = 2565312KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BusStopManagement] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BusStopManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BusStopManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BusStopManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BusStopManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BusStopManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BusStopManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [BusStopManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BusStopManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BusStopManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BusStopManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BusStopManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BusStopManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BusStopManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BusStopManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BusStopManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BusStopManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BusStopManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BusStopManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BusStopManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BusStopManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BusStopManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BusStopManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BusStopManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BusStopManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [BusStopManagement] SET  MULTI_USER 
GO

ALTER DATABASE [BusStopManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BusStopManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BusStopManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BusStopManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BusStopManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BusStopManagement] SET QUERY_STORE = OFF
GO

USE [BusStopManagement]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [BusStopManagement] SET  READ_WRITE 
GO

